"""
pairwise_potential.py — the N-body / particle potential V(q | ctx).

Irregular-node systems (particles, no grid) break the periodic-domain
assumption behind the FNO spectral layer in OperatorPotential, so the correct
energy structure is a PAIR potential:

    V(q) = sum_{i<j} phi(q_i - q_j | ctx)

Translation-invariant (depends only on differences) and permutation-invariant
(sum over unordered pairs) — the two symmetries any particle energy must
respect. phi is a smooth (Tanh) MLP so the Hamiltonian field dV/dq is C^2.
Context conditions phi by concatenation (the inferred mass distribution, e.g.).

This is the P2-1 building block: it makes the hard-constraint Hamiltonian
applicable to gravitational N-body / collision systems generated by
datasets.gen_nbody.
"""

from __future__ import annotations

from typing import Optional

import torch
import torch.nn as nn


def _energy_mlp(dim: int, hidden_dim: int, depth: int) -> nn.Sequential:
    layers: list[nn.Module] = []
    d = dim
    for _ in range(depth):
        layers += [nn.Linear(d, hidden_dim), nn.Tanh()]
        d = hidden_dim
    layers += [nn.Linear(d, 1)]
    return nn.Sequential(*layers)


class PairwisePotential(nn.Module):
    """V(q | ctx) = sum_{i<j} phi(|q_i - q_j| ; ctx), q: (B, N, dim).

    RADIAL pair potential: phi sees only the distance |q_i - q_j|, so the energy
    is translation-, permutation- AND rotation-invariant (the three symmetries
    of a central-force system like gravity / Lennard-Jones). A vector-input phi
    would NOT be permutation-invariant unless it were even — the radial form
    sidesteps that entirely and matches the physics of the N-body generator."""

    def __init__(self, dim: int, hidden_dim: int = 64, depth: int = 2,
                 context_dim: int = 0):
        super().__init__()
        self.dim = int(dim)
        self.context_dim = int(context_dim)
        self.phi = _energy_mlp(1 + context_dim, hidden_dim, depth)

    def forward(self, q: torch.Tensor,
                context: Optional[torch.Tensor] = None) -> torch.Tensor:
        B, N, D = q.shape
        assert D == self.dim, f"q has dim {D}, potential expects {self.dim}"
        diff = q.unsqueeze(2) - q.unsqueeze(1)               # (B, N, N, D)
        i, j = torch.triu_indices(N, N, offset=1)            # upper triangle i < j
        r = diff[:, i, j].norm(dim=-1, keepdim=True)         # (B, M, 1) distances
        if context is not None:
            ctx = context.unsqueeze(1).expand(-1, r.shape[1], -1)
            r = torch.cat([r, ctx], dim=-1)
        e = self.phi(r).squeeze(-1)                          # (B, M)
        return e.sum(dim=1)                                  # (B,)
